"""Skill: cta_analysis — where the funnel's public entry point sits, if it exists."""

from app.skills.cta_analysis.schemas import (
    FOLD_LINES,
    THIN_SLICE,
    WRAP_COLUMNS,
    CtaCoverage,
    CtaLineStat,
    CtaReport,
    DomainStat,
    LinkKind,
    LinkPlacement,
    PlacementStat,
    TrackingState,
    VideoDescription,
)
from app.skills.cta_analysis.skill import (
    SHORTENER_DOMAINS,
    SOCIAL_DOMAINS,
    CtaAnalysisError,
    aggregate_placements,
    analyse_cta,
    classify_domain,
    cta_template,
    extract_links,
    normalise_domain,
    pick_primary_domain,
    rendered_line_of,
    tracking_state,
)

__all__ = [
    "FOLD_LINES",
    "SHORTENER_DOMAINS",
    "SOCIAL_DOMAINS",
    "THIN_SLICE",
    "WRAP_COLUMNS",
    "CtaAnalysisError",
    "CtaCoverage",
    "CtaLineStat",
    "CtaReport",
    "DomainStat",
    "LinkKind",
    "LinkPlacement",
    "PlacementStat",
    "TrackingState",
    "VideoDescription",
    "aggregate_placements",
    "analyse_cta",
    "classify_domain",
    "cta_template",
    "extract_links",
    "normalise_domain",
    "pick_primary_domain",
    "rendered_line_of",
    "tracking_state",
]
